// Generated by CoffeeScript 2.4.1
(function() {
  var Demo;

  Demo = class Demo {
    constructor() {
      console.log('hello from demo');
    }

    init() {
      console.log('init...');
      $.ajax({
        url: 'http://localhost:8080/api/hello-world',
        success: function(data) {
          var jsonDataString;
          jsonDataString = JSON.stringify(data);
          return $('#data-area').text(jsonDataString);
        },
        error: function(error) {
          return console.log('cry me a river %s', error);
        }
      });
      return console.log('after init...');
    }

  };

  $('document').ready(function() {
    var demo;
    demo = new Demo();
    return demo.init();
  });

}).call(this);
